name: Build Kivy APK

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git python3 python3-dev zip unzip libtool libtool-bin autoconf automake m4 pkg-config libffi-dev libssl-dev openjdk-17-jdk
          pip install --upgrade pip
          pip install buildozer cython==0.29.33
      
      - name: Pre-patch Server & Build APK
        run: |
          # 1. Kloning sistem perakit Android secara manual
          mkdir -p .buildozer/android/platform
          git clone -b master --single-branch https://github.com/kivy/python-for-android.git .buildozer/android/platform/python-for-android || true
          
          # 2. Injeksi bypass server Savannah ke server Kanada (Mirror) agar terhindar dari 502/504
          find .buildozer/android/platform/python-for-android -type f -name "__init__.py" -exec sed -i 's/download.savannah.gnu.org\/releases/mirror.csclub.uwaterloo.ca\/nongnu/g' {} + || true
          
          # 3. Eksekusi perakitan
          yes | buildozer -v android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: aplikasi-skripsi
          path: bin/*.apk
